### ISSUE TITLE
multipolygon function incompatible with newer matplotlib packages

### ISSUE THREAD

**Issue by werner2101** [werner2101/python-osm#17]
with matplotlib 1.4.2 i got following error:

<pre>
Traceback (most recent call last):
  File "./places.py", line 9, in <module>
    from osm import multipolygon
  File "python-osm/src/osm/multipolygon.py", line 6, in <module>
    import matplotlib.nxutils
ImportError: No module named nxutils
</pre>

**Comment by werner2101** [comment]
nxutils is used for points_inside_poly calculation.

The function is deprecated. And no longer part of matplotlib since version 1.3.x. see:

http://matplotlib.org/1.2.1/api/nxutils_api.html
